### ISSUE TITLE
Multiple issues during set up a project

### ISSUE THREAD

**Issue by kubk** [hannah-developer/timezoneconverter_react#1]
Hi, thank you for the interesting project. I encountered multiple issues during setting up the project:

1. `./src/style.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/style.css)
Error: Can't resolve './fonts/Soleil-Regular.TTF' in '/home/nastay/projects/timezoneconverter_react/src'`
2. `Module not found: Can't resolve './zones' in '/home/*/projects/timezoneconverter_react/src/components'`

Steps to reproduce:
1. Copy the project via `git clone`, install dependencies using `npm i` and run the project `npm run start`

**Comment by hannah-choi** [comment]
Hi, thanks for reaching me and letting me know. 
FYI, I intentionally ignored those two files from git. 
Font file to avoid possible piracy issue, and the zone.js for the further fix.
I'll make the code work without it soon. 
Hope it helps.
